# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yob', models.IntegerField(verbose_name='When were you born?')),
                ('australian', models.BooleanField(verbose_name='Do you live in Australia?')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='If you live in Australia, what is your postcode?')),
                ('background', models.CharField(choices=[(0, 'deaf community'), (1, 'Auslan teacher'), (2, 'teacher of the deaf'), (3, 'parent of a deaf child'), (4, 'sign language interpreter'), (5, 'school or college student (under 18)'), (6, 'student learning Auslan'), (9, 'university student (taught, e.g. BA, BSc, MA, Msc)'), (10, 'university student (research, e.g. PhD)'), (8, 'university academic/research staff'), (7, 'other')], max_length=20, verbose_name='What is your background?')),
                ('researcher_credentials', models.TextField(verbose_name='Research credentials')),
                ('auslan_user', models.BooleanField(verbose_name='Do you use Auslan?')),
                ('learned', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'At home from my parent(s)'), (2, 'At kindergarten or at the beginning of primary school'), (3, 'At primary school'), (4, 'At high school'), (5, 'After I left school')], verbose_name='If you use Auslan, when did you learn sign language?')),
                ('deaf', models.BooleanField(verbose_name='Are you a deaf person?')),
                ('schooltype', models.IntegerField(choices=[(0, 'a deaf school (boarder)'), (1, 'a deaf school (day student)'), (2, 'a deaf classroom or unit in a hearing school'), (3, 'a regular classroom in a hearing school')], verbose_name='What sort of school do you (or did you) attend?')),
                ('school', models.CharField(blank=True, max_length=50, verbose_name='Which school do you (or did you) attend?')),
                ('teachercomm', models.IntegerField(choices=[(0, 'mostly oral'), (1, 'mostly Signed English'), (2, 'mostly sign language (Auslan)'), (3, 'mostly fingerspelling'), (4, 'N/A, I am hearing')], verbose_name='How do (or did) your teachers communicate with you?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
